In [7]:
from pydub import AudioSegment
import librosa
import math
import pandas as pd
import numpy as np
import os

def features_extractor(file):
    audio, sample_rate = librosa.load(file, res_type='kaiser_fast') 
    mfccs_features = librosa.feature.mfcc(y=audio, sr=sample_rate, n_mfcc=40)
    mfccs_scaled_features = np.mean(mfccs_features.T,axis=0)
    
    return mfccs_scaled_features

In [8]:
extracted_features=[]
def auidoFileData(fileName):
    print(fileName)
    path = 'data2/' + fileName + '/converted/splitted/'
    audioNames = os.listdir(path)
    folderFileCount = len(audioNames)
    for i in range(0, folderFileCount - 1):
        print(path+audioNames[i])
        final_class_labels=fileName
        data=features_extractor(path+audioNames[i])
        #print(i, ' - ', path+audioNames[i], ' - ', data)
        extracted_features.append([data,final_class_labels])
        

In [9]:
path = 'data2/'
#otherPath = path + 'splittedAllAudioFiles/'
fileNames = os.listdir(path)
counter=1
for i in range(0, len(fileNames)-1):
    if fileNames[i] != 'diger':
        counter = 1
        auidoPath = path+fileNames[i]
        audioFileNames = os.listdir(auidoPath)
        
        
        for j in range(0, len(audioFileNames)-1):
            if audioFileNames[j] != 'splitted':    
                if audioFileNames[j] != 'converted':
                    #print(auidoPath+'/splitted/'+audioFileNames[j])

                    audioFileBadName = audioFileNames[j].split('.')[0]
                    print(audioFileNames[j])
                    print(auidoPath+'/'+audioFileBadName+".wav")

                    song = AudioSegment.from_wav(auidoPath+'/converted/'+audioFileBadName+".wav")

                    duration = song.duration_seconds
                    for k in range(int(duration/5)):
                        splitted_audio = song[(5*k)*1000:(5*k+1)*1000]
                        splitted_audio.export(auidoPath+'/converted/splitted/'+audioFileBadName+str(counter)+'.wav', format="wav")
                        #print(auidoPath+'/splitted/'+audioFile+str(counter)+'.wav',)

                        counter=counter+1
        print('------------------')
        auidoFileData(fileNames[i])
        print('------------------')

beeBird1.mp3
data2/beeBird/beeBird1.wav
beeBird10.mp3
data2/beeBird/beeBird10.wav
beeBird11.mp3
data2/beeBird/beeBird11.wav
beeBird12.mp3
data2/beeBird/beeBird12.wav
beeBird13.mp3
data2/beeBird/beeBird13.wav
beeBird14.mp3
data2/beeBird/beeBird14.wav
beeBird15.mp3
data2/beeBird/beeBird15.wav
beeBird16.mp3
data2/beeBird/beeBird16.wav
beeBird17.mp3
data2/beeBird/beeBird17.wav
beeBird2.mp3
data2/beeBird/beeBird2.wav
beeBird3.mp3
data2/beeBird/beeBird3.wav
beeBird4.mp3
data2/beeBird/beeBird4.wav
beeBird5.mp3
data2/beeBird/beeBird5.wav
beeBird6.mp3
data2/beeBird/beeBird6.wav
beeBird7.mp3
data2/beeBird/beeBird7.wav
beeBird8.mp3
data2/beeBird/beeBird8.wav
beeBird9.mp3
data2/beeBird/beeBird9.wav
------------------
beeBird
data2/beeBird/converted/splitted/beeBird1013.wav
data2/beeBird/converted/splitted/beeBird1014.wav
data2/beeBird/converted/splitted/beeBird1015.wav
data2/beeBird/converted/splitted/beeBird1016.wav
data2/beeBird/converted/splitted/beeBird1017.wav
data2/beeBird/converted/splitted

In [37]:
#counter = 1
#audioOutputPath = "data/beeBird/converted/splitted/"
#for i in range(1, 19):
#    if i != 2:
#        song = AudioSegment.from_wav("data/ham/beeBird/converted/beeBird"+str(i)+".wav")
#        duration = song.duration_seconds
#        for j in range(int(duration/5)):
#            splitted_audio = song[(5*j)*1000:5*(j+1)*1000]
#            #splitted_audio.export("data/ham/beeBird/converted/splitted/named/beeBird"+str(i)+"Splitted"+str(j)+".wav", format="wav")
#            splitted_audio.export(audioOutputPath+"beeBird"+str(counter)+".wav", format="wav")
#            print("data/ham/beeBird/converted/splitted/named/beeBird"+str(counter)+".wav")

#            counter=counter+1

In [10]:
extracted_features_df=pd.DataFrame(extracted_features,columns=['feature','class'])
extracted_features_df.head()

feature    class
0  [-663.9164, 7.463325, -62.418396, -11.28446, 2...  beeBird
1  [-516.3681, 20.667408, -156.5519, -22.70332, 5...  beeBird
2  [-469.1672, 9.647738, -137.6997, -10.3834715, ...  beeBird
3  [-635.8646, 15.384795, -160.60805, -9.371105, ...  beeBird
4  [-500.93127, 8.004455, -151.3385, -17.601057, ...  beeBird

In [ ]:
extracted_features_df.to_csv('audioData.csv', sep=',', index=None);

In [62]:
X=np.array(extracted_features_df['feature'].tolist())
y=np.array(extracted_features_df['class'].tolist())


In [63]:
y

array(['beeBird', 'beeBird', 'beeBird', ..., 'pigeon', 'pigeon', 'pigeon'],
      dtype='<U11')

In [64]:
X

array([[-6.6391638e+02,  7.4633250e+00, -6.2418396e+01, ...,
        -1.1986932e+00,  1.0940291e+00,  5.3446740e-01],
       [-5.1636810e+02,  2.0667408e+01, -1.5655190e+02, ...,
        -1.2560490e+00,  2.2411509e+00, -7.2818774e-01],
       [-4.6916721e+02,  9.6477385e+00, -1.3769971e+02, ...,
        -1.6974189e+00,  3.5586610e+00, -6.6746134e-01],
       ...,
       [-2.8436514e+02,  1.3251250e+02,  4.2366329e+01, ...,
        -1.5910071e+00, -1.6375576e+00, -3.5378973e+00],
       [-2.8264023e+02,  9.9185661e+01,  2.9451946e+01, ...,
        -2.4407899e+00, -3.2088995e+00, -1.9700946e+00],
       [-2.8411053e+02,  8.0845634e+01,  6.7474918e+00, ...,
        -2.1589963e+00, -2.5575335e+00, -2.9223695e+00]], dtype=float32)

In [65]:
from tqdm import tqdm

from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.optimizers import Adam

from sklearn import metrics
from tensorflow.keras.callbacks import ModelCheckpoint
from datetime import datetime

In [87]:
labelencoder=LabelEncoder()
yNew=to_categorical(labelencoder.fit_transform(y))
yNew

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [67]:
xtrain, xtest, ytrain, ytest = train_test_split(X, yNew, test_size=0.2, random_state=0)

In [68]:
num_labels=9

In [69]:
model=Sequential()
model.add(Dense(125, input_shape=(40,)))
model.add(Activation('relu'))
model.add(Dropout(0.5))

#2. gizli
model.add(Dense(250))
model.add(Activation('relu'))
model.add(Dropout(0.5))

#3. gizli
model.add(Dense(125))
model.add(Activation('relu'))
model.add(Dropout(0.5))

#output
model.add(Dense(num_labels))
model.add(Activation('softmax'))

In [70]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 125)               5125      
                                                                 
 activation_4 (Activation)   (None, 125)               0         
                                                                 
 dropout_3 (Dropout)         (None, 125)               0         
                                                                 
 dense_5 (Dense)             (None, 250)               31500     
                                                                 
 activation_5 (Activation)   (None, 250)               0         
                                                                 
 dropout_4 (Dropout)         (None, 250)               0         
                                                                 
 dense_6 (Dense)             (None, 125)              

In [71]:
model.compile(loss='categorical_crossentropy', metrics=["accuracy"], optimizer="adam")

In [72]:
epochscount=300
num_batch_size=32

In [74]:
model.fit(xtrain, ytrain, batch_size=num_batch_size, epochs=epochscount, validation_data=(xtest, ytest), verbose=1)

Epoch 1/300
54/54 [==============================] - 1s 4ms/step - loss: 29.1251 - accuracy: 0.2683 - val_loss: 1.4249 - val_accuracy: 0.5058
Epoch 2/300
54/54 [==============================] - 0s 3ms/step - loss: 8.8942 - accuracy: 0.3490 - val_loss: 1.4861 - val_accuracy: 0.4200
Epoch 3/300
54/54 [==============================] - 0s 3ms/step - loss: 4.8109 - accuracy: 0.4007 - val_loss: 1.5601 - val_accuracy: 0.4037
Epoch 4/300
54/54 [==============================] - 0s 3ms/step - loss: 3.1815 - accuracy: 0.4065 - val_loss: 1.6367 - val_accuracy: 0.3550
Epoch 5/300
54/54 [==============================] - 0s 4ms/step - loss: 2.4439 - accuracy: 0.4315 - val_loss: 1.5148 - val_accuracy: 0.4014
Epoch 6/300
54/54 [==============================] - 0s 3ms/step - loss: 1.9872 - accuracy: 0.4988 - val_loss: 1.4502 - val_accuracy: 0.6241
Epoch 7/300
54/54 [==============================] - 0s 3ms/step - loss: 1.7249 - accuracy: 0.5221 - val_loss: 1.4234 - val_accuracy: 0.6241
Epoch 8/300


In [76]:
validation_test_set_accuracy=model.evaluate(xtest, ytest, verbose=0)
print(validation_test_set_accuracy[1])

0.9814385175704956


In [77]:
xtest[1]

array([-2.8373059e+02,  1.0526962e+02,  3.4451218e+01,  5.5258396e+01,
       -3.0436552e+01,  1.4635709e+01, -3.0520094e+01, -1.1657702e+01,
       -1.7823097e+01, -3.0396476e+00, -1.2944512e+01,  5.7842860e+00,
       -1.2763754e+01,  8.4384747e+00, -1.1972279e+01,  3.6598494e+00,
       -8.7228966e+00, -2.0704946e-01, -3.9429481e+00, -6.3000351e-02,
       -6.4605575e+00,  2.1987450e+00, -7.2112737e+00,  2.7235341e+00,
       -1.7863247e+00,  2.8759515e+00,  1.7259520e+00,  2.1138479e-01,
        1.0838553e+00,  4.8017282e+00,  7.4913752e-01,  3.8533278e+00,
       -1.9259442e+00, -5.7181430e-01, -4.1760077e+00, -5.0560517e+00,
       -3.4229281e+00, -5.6647282e+00, -4.2859941e+00, -2.7654414e+00],
      dtype=float32)

In [78]:
fileName = "./testData/nightingale131.wav"

In [79]:
testDataResult = features_extractor(fileName)

In [80]:
testDataResult=testDataResult.reshape(1, -1)
testDataResult.shape

(1, 40)

In [81]:
result_array=model.predict(testDataResult)

In [82]:
result_array

array([[1.7482034e-10, 5.9651030e-16, 1.1651580e-19, 8.3602820e-17,
        6.9948179e-26, 1.5936358e-16, 1.0000000e+00, 1.2249193e-19,
        4.2405550e-12]], dtype=float32)

In [83]:
resultClasses=["beeBird", "eagle", "hawk", "hoopoe", "hummingBird", "littleOwl", "nightingale", "parrot", "pigeon"]
resultClasses

['beeBird',
 'eagle',
 'hawk',
 'hoopoe',
 'hummingBird',
 'littleOwl',
 'nightingale',
 'parrot',
 'pigeon']

In [84]:
result=np.argmax(result_array[0])
result

6

In [85]:
from IPython.display import Audio
Audio(fileName)

In [86]:
resultClasses[result]

'nightingale'