In [15]:
import pandas as pd 
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import numpy as np

from sklearn import metrics

In [3]:
data=pd.read_csv("../audioData.csv",encoding="ISO-8859-1")
col_name=['features', 'class']
data.columns=col_name
data.head()


features    class
0  [-6.6391638e+02  7.4633250e+00 -6.2418396e+01 ...  beeBird
1  [-5.16368103e+02  2.06674080e+01 -1.56551895e+...  beeBird
2  [-469.1672        9.647738   -137.6997      -1...  beeBird
3  [-6.3586462e+02  1.5384795e+01 -1.6060805e+02 ...  beeBird
4  [-5.0093127e+02  8.0044546e+00 -1.5133850e+02 ...  beeBird

In [6]:
X=data['features']
y=data['class']
print(X)
print(y)


0       [-6.6391638e+02  7.4633250e+00 -6.2418396e+01 ...
1       [-5.16368103e+02  2.06674080e+01 -1.56551895e+...
2       [-469.1672        9.647738   -137.6997      -1...
3       [-6.3586462e+02  1.5384795e+01 -1.6060805e+02 ...
4       [-5.0093127e+02  8.0044546e+00 -1.5133850e+02 ...
                              ...                        
2148    [-3.32472534e+02  1.16614426e+02  4.51772957e+...
2149    [-262.14792      83.66872      14.975486     5...
2150    [-284.36514     132.5125       42.36633      5...
2151    [-282.64023      99.18566      29.451946     5...
2152    [-284.11053      80.845634      6.747492     6...
Name: features, Length: 2153, dtype: object
0       beeBird
1       beeBird
2       beeBird
3       beeBird
4       beeBird
         ...   
2148     pigeon
2149     pigeon
2150     pigeon
2151     pigeon
2152     pigeon
Name: class, Length: 2153, dtype: object


In [13]:
import re
newX = []
for j in range(0, len(data['features'])):
    #print(j, data['feature'][j], )
    newP = []
    for i in data['features'][j].replace('\n', '').split(' '):
        if i != '':
            try:
                #print(float( re.sub("[^\d\.]", "", i)))
                newP.append(float( re.sub("[^\d\.]", "", i)))
            except:
                print(j, 'isnt ok.')
                continue
    
    print(j, 'is ok.')
    newX.append(newP)

0 is ok.
1 is ok.
2 is ok.
3 is ok.
4 is ok.
5 is ok.
6 isnt ok.
6 is ok.
7 is ok.
8 is ok.
9 isnt ok.
9 is ok.
10 is ok.
11 is ok.
12 is ok.
13 is ok.
14 is ok.
15 is ok.
16 is ok.
17 is ok.
18 is ok.
19 is ok.
20 is ok.
21 is ok.
22 is ok.
23 is ok.
24 is ok.
25 is ok.
26 is ok.
27 is ok.
28 is ok.
29 is ok.
30 is ok.
31 is ok.
32 is ok.
33 is ok.
34 is ok.
35 is ok.
36 is ok.
37 isnt ok.
37 is ok.
38 is ok.
39 is ok.
40 is ok.
41 is ok.
42 is ok.
43 isnt ok.
43 is ok.
44 is ok.
45 isnt ok.
45 is ok.
46 is ok.
47 isnt ok.
47 is ok.
48 is ok.
49 isnt ok.
49 is ok.
50 is ok.
51 is ok.
52 isnt ok.
52 is ok.
53 is ok.
54 isnt ok.
54 is ok.
55 is ok.
56 is ok.
57 is ok.
58 is ok.
59 is ok.
60 is ok.
61 is ok.
62 isnt ok.
62 is ok.
63 is ok.
64 is ok.
65 is ok.
66 is ok.
67 is ok.
68 is ok.
69 is ok.
70 isnt ok.
70 is ok.
71 is ok.
72 isnt ok.
72 is ok.
73 is ok.
74 is ok.
75 is ok.
76 is ok.
77 is ok.
78 isnt ok.
78 is ok.
79 is ok.
80 is ok.
81 is ok.
82 is ok.
83 is ok.
84 is ok.
85 is 

In [17]:
newX = np.array(newX)
newX.shape

(2153, 40)

In [18]:
X_train, X_test, y_train,y_test= train_test_split(newX,y, test_size=0.2, random_state=1)
print(X_test)

[[4.69493134 3.92696991 1.3059584  ... 4.13796335 4.57612485 3.88651825]
 [3.1176022  7.510894   1.0095074  ... 1.8033543  5.2108159  1.7591838 ]
 [3.5867819  9.0817055  2.7590168  ... 2.06303    6.2901216  7.5679338 ]
 ...
 [2.87827087 8.59204712 1.47493534 ... 2.72041035 3.05776525 3.40456319]
 [2.7334518  1.0621814  3.4681278  ... 3.0520582  3.3619006  8.9240777 ]
 [3.0569763  9.5565987  3.1038782  ... 2.5067596  1.3954505  6.2338632 ]]


In [23]:
dt=DecisionTreeClassifier()
dt=dt.fit(X_train,y_train)

In [24]:
y_pred=dt.predict(X_test)
print("Acc",metrics.accuracy_score(y_test,y_pred))

Acc 0.7308584686774942


In [25]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print(cm)

[[ 36   0   3   0   1   1  12   2   3]
 [  1   4   4   1   1   1   1   1   1]
 [  4   1  14   2   0   0   2   2   1]
 [  1   1   2   0   1   1   1   0   1]
 [  0   1   0   0  16   0   0   0   0]
 [  0   3   0   0   0   2   2   0   0]
 [ 10   4   6   4   0   0 109   4   0]
 [  0   1   3   2   0   0  14   5   2]
 [  1   0   2   0   0   0   2   2 129]]


In [26]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

In [33]:
accuracy=accuracy_score(y_test, y_pred)
precision=precision_score(y_test, y_pred, average='macro')
recall=recall_score(y_test, y_pred, average='macro')
fmeasure=f1_score(y_test, y_pred, average='macro')

In [36]:
print(accuracy)
print(precision)
print(recall)
print(fmeasure)

0.7308584686774942
0.5129028355977336
0.509115961278804
0.5067098574850513
